# Generated by Django 3.1.7 on 2021-10-21 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apc',
            fields=[
                ('nom_APC', models.CharField(default='test', max_length=50, primary_key=True, serialize=False)),
                ('commune', models.ForeignKey(default='test', on_delete=django.db.models.deletion.CASCADE, to='api.commune')),
            ],
        ),
        migrations.AddField(
            model_name='panneau',
            name='apc',
            field=models.ForeignKey(default='test', on_delete=django.db.models.deletion.CASCADE, to='api.apc'),
        ),
    ]
