# Generated by Django 3.1.7 on 2021-10-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211021_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apc',
            name='nom_APC',
            field=models.CharField(default='cheraga', max_length=50, primary_key=True, serialize=False),
        ),
    ]
