# Generated by Django 3.1.7 on 2021-10-21 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211021_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apc',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.commune'),
        ),
        migrations.AlterField(
            model_name='apc',
            name='nom_APC',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='panneau',
            name='apc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.apc'),
        ),
    ]
