# Generated by Django 3.1.7 on 2021-10-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211021_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='afficheur',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='afficheur',
            name='nom_afficheur',
            field=models.CharField(max_length=30),
        ),
    ]
