# Generated by Django 3.1.7 on 2021-10-25 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211025_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apc',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='commune',
            name='Wilaya',
        ),
        migrations.RemoveField(
            model_name='panneau',
            name='afficheur',
        ),
        migrations.RemoveField(
            model_name='panneau',
            name='apc',
        ),
        migrations.RemoveField(
            model_name='panneau',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='panneau',
            name='wilaya',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='panneau',
        ),
        migrations.DeleteModel(
            name='Afficheur',
        ),
        migrations.DeleteModel(
            name='Apc',
        ),
        migrations.DeleteModel(
            name='Commune',
        ),
        migrations.DeleteModel(
            name='Panneau',
        ),
        migrations.DeleteModel(
            name='Pub',
        ),
        migrations.DeleteModel(
            name='Wilaya',
        ),
    ]
