# Generated by Django 3.1.7 on 2021-10-25 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211025_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonceur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100, unique=True)),
                ('Logo', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100, unique=True)),
                ('Logo', models.ImageField(upload_to='')),
                ('NomAnnonceur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.annonceur')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100, unique=True)),
                ('Logo', models.ImageField(upload_to='')),
                ('NomMarque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.marque')),
            ],
        ),
    ]
