# Generated by Django 3.1.7 on 2021-10-27 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_annonceur_marque_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomJournal', models.CharField(default='', max_length=20, unique=True)),
                ('image', models.ImageField(default='', upload_to='media')),
            ],
        ),
        migrations.AddField(
            model_name='panneau',
            name='image',
            field=models.ImageField(default='', upload_to='media'),
        ),
        migrations.AddField(
            model_name='pub',
            name='image',
            field=models.ImageField(default='', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='annonceur',
            name='Logo',
            field=models.ImageField(default='', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='marque',
            name='Logo',
            field=models.ImageField(default='', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='Logo',
            field=models.ImageField(default='', upload_to='media'),
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('numero', models.IntegerField()),
                ('image', models.ImageField(default='', upload_to='media')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.journal')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='media')),
                ('date_creation', models.DateTimeField()),
                ('language', models.CharField(choices=[('AR', 'arabe'), ('FR', 'francais')], default='', max_length=2)),
                ('accroche', models.CharField(default='', max_length=1000)),
                ('page_suivante', models.CharField(choices=[('s', 'sport'), ('p', 'politeque'), ('c', 'culture')], default='', max_length=1)),
                ('page_precedente', models.CharField(choices=[('s', 'sport'), ('p', 'politeque'), ('c', 'culture')], default='', max_length=1)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.edition')),
            ],
        ),
    ]
