# Generated by Django 3.1.7 on 2021-10-27 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211027_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100, unique=True)),
                ('service', models.CharField(choices=[('J', 'Journal'), ('P', 'Panneau')], default='', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='pub',
            name='annonceur',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='marque',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='produit',
        ),
        migrations.AddField(
            model_name='article',
            name='produit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.produit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pub',
            name='prod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.produit'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.produit')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service')),
            ],
        ),
    ]
