# Generated by Django 3.1.7 on 2021-10-27 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20211027_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='service',
            new_name='abonnement',
        ),
    ]
