# Generated by Django 3.1.7 on 2021-11-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20211109_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commune',
            name='Wilaya',
        ),
        migrations.RemoveField(
            model_name='panneau',
            name='afficheur',
        ),
        migrations.RemoveField(
            model_name='panneau',
            name='apc',
        ),
        migrations.RemoveField(
            model_name='panneau',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='panneau',
            name='wilaya',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='panneau',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='prod',
        ),
        migrations.AlterField(
            model_name='edition',
            name='date',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Apc',
        ),
        migrations.DeleteModel(
            name='Commune',
        ),
        migrations.DeleteModel(
            name='Panneau',
        ),
        migrations.DeleteModel(
            name='Pub',
        ),
        migrations.DeleteModel(
            name='Wilaya',
        ),
    ]
