# Generated by Django 3.1.7 on 2021-11-16 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20211116_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_APC', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Panneau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('type1', 'type1'), ('type2', 'type2'), ('type3', 'type3')], max_length=20)),
                ('itineraire', models.CharField(max_length=20)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField()),
                ('designation', models.CharField(max_length=40)),
                ('nombre_facette', models.IntegerField()),
                ('hauteur', models.FloatField()),
                ('largeur', models.FloatField()),
                ('elevation', models.FloatField()),
                ('mecanisme', models.CharField(choices=[('mec1', 'mec1'), ('mec2', 'mec2'), ('mec3', 'mec3')], max_length=20)),
                ('circulation', models.BooleanField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='', upload_to='media')),
                ('afficheur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.afficheur')),
                ('apc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.apc')),
            ],
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_wilaya', models.CharField(max_length=30)),
                ('num_wilaya', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langue', models.CharField(choices=[('fr', 'fr'), ('ar', 'ar'), ('fr + ar', 'fr + ar')], max_length=20)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(default='', upload_to='media')),
                ('panneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.panneau')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_commune', models.CharField(max_length=50)),
                ('Wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wilaya')),
            ],
        ),
        migrations.AddField(
            model_name='apc',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.commune'),
        ),
    ]
