# Generated by Django 3.1.7 on 2021-11-28 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0017_auto_20211118_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='produit',
        ),
        migrations.AddField(
            model_name='abonnement',
            name='client',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='produits',
            field=models.ManyToManyField(to='api.Produit'),
        ),
    ]
