# Generated by Django 3.1.7 on 2021-11-28 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20211128_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='annonceur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.annonceur'),
        ),
        migrations.AddField(
            model_name='article',
            name='marque',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.marque'),
        ),
        migrations.AlterField(
            model_name='article',
            name='produit',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.produit'),
        ),
    ]
