# Generated by Django 3.1.7 on 2021-11-28 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20211128_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='annonceur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.annonceur'),
        ),
        migrations.AlterField(
            model_name='article',
            name='marque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.marque'),
        ),
        migrations.AlterField(
            model_name='article',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.produit'),
        ),
    ]
