# Generated by Django 3.1.7 on 2021-12-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20211129_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='accroche',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
