# Generated by Django 3.1.7 on 2021-12-05 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20211201_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pub',
            name='prod',
        ),
        migrations.AddField(
            model_name='pub',
            name='annonceur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.annonceur'),
        ),
        migrations.AddField(
            model_name='pub',
            name='marque',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.marque'),
        ),
        migrations.AddField(
            model_name='pub',
            name='produit',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.produit'),
        ),
    ]
