# Generated by Django 3.1.7 on 2021-12-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20211209_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='panneau',
            name='nbpub',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='panneau',
            name='mecanisme',
            field=models.CharField(choices=[('Dérouleur', 'Dérouleur'), ('Trivision', 'Trivision'), ('Fix', 'Fix')], max_length=20),
        ),
        migrations.AlterField(
            model_name='panneau',
            name='type',
            field=models.CharField(choices=[('Simple', 'Simple'), ('Unipol', 'Unipol'), ('Sucette', 'Sucette'), ('Abri-Bus', 'Abri-Bus'), ('Bus', 'Bus'), ('Sucette dynamique', 'Sucette dynamique'), ('Terasse', 'Terasse'), ('Fassade', 'Fassade')], max_length=20),
        ),
    ]
