# Generated by Django 3.1.7 on 2021-12-12 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20211209_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chaine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=20, unique=True)),
                ('image', models.ImageField(default='', upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='VideoPub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(default='', upload_to='media')),
                ('date_creation', models.DateField()),
                ('language', models.CharField(choices=[('AR', 'arabe'), ('FR', 'francais')], default='', max_length=2)),
                ('accroche', models.CharField(default='', max_length=10000)),
                ('confirmed', models.BooleanField(default=False)),
                ('annonceur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.annonceur')),
                ('chaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chaine')),
                ('marque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.marque')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.produit')),
            ],
        ),
    ]
